# Generated by Django 3.1.4 on 2021-02-17 13:11

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 17, 13, 11, 37, 500114)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 17, 13, 11, 37, 499640)),
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
